In [1]:
import sys, os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.layers import Dense, Dropout, SimpleRNN, LSTM
from keras.models import Sequential
sys.path.append(os.path.join(os.path.dirname('Demand'), '..', 'src'))
import Demand

In [2]:
path = '../data/demand_lower_48'

In [3]:
national_demand = Demand.Demand()

In [5]:
national_demand.load_and_clean_data(path)

In [6]:
national_demand.dataframe.head()

Megawatthours  Year  Month  Hour  Day_of_week  \
Time                                                                 
2015-07-01 02:00:00         335153  2015      7     2            2   
2015-07-01 03:00:00         333837  2015      7     3            2   
2015-07-01 04:00:00         398386  2015      7     4            2   
2015-07-01 05:00:00         388954  2015      7     5            2   
2015-07-01 06:00:00         392487  2015      7     6            2   

                     Day_of_month  Day_of_year  
Time                                            
2015-07-01 02:00:00             1          182  
2015-07-01 03:00:00             1          182  
2015-07-01 04:00:00             1          182  
2015-07-01 05:00:00             1          182  
2015-07-01 06:00:00             1          182

In [8]:
df = pd.DataFrame(national_demand.dataframe['Megawatthours'])

In [10]:
df.head()

Megawatthours
Time                              
2015-07-01 02:00:00         335153
2015-07-01 03:00:00         333837
2015-07-01 04:00:00         398386
2015-07-01 05:00:00         388954
2015-07-01 06:00:00         392487

In [11]:
split_date = '2020-07-01 00:00:00'

In [17]:
train = df.loc[:split_date]
test = df.loc[split_date:]

In [18]:
scaler = MinMaxScaler()

In [19]:
train_scaled = scaler.fit_transform(train)

In [20]:
test_scaled = scaler.fit_transform(test)

In [22]:
train_scaled

array([[0.14192568],
       [0.13897496],
       [0.28370561],
       ...,
       [0.67980063],
       [0.62285591],
       [0.55047602]])

In [23]:
test_scaled

array([[0.53741909],
       [0.45518111],
       [0.38075803],
       ...,
       [0.17596966],
       [0.19581018],
       [0.22196178]])

In [26]:
def load_data(train, test, seq_len):
    X_train = []
    y_train = []
    for i in range(seq_len, len(train)):
        X_train.append(train[i-seq_len : i, 0])
        y_train.append(train[i, 0])
    
    return X_train, y_train

In [27]:
X_train, y_train = load_data(train_scaled, test_scaled, 20)

In [28]:
X_train

[array([0.14192568, 0.13897496, 0.28370561, 0.26255734, 0.27047898,
        0.29774392, 0.33716149, 0.38178989, 0.43165603, 0.49251111,
        0.55199846, 0.60238254, 0.64764548, 0.68284551, 0.70752073,
        0.72337744, 0.72509271, 0.70508123, 0.67445078, 0.63414979]),
 array([0.13897496, 0.28370561, 0.26255734, 0.27047898, 0.29774392,
        0.33716149, 0.38178989, 0.43165603, 0.49251111, 0.55199846,
        0.60238254, 0.64764548, 0.68284551, 0.70752073, 0.72337744,
        0.72509271, 0.70508123, 0.67445078, 0.63414979, 0.60870101]),
 array([0.28370561, 0.26255734, 0.27047898, 0.29774392, 0.33716149,
        0.38178989, 0.43165603, 0.49251111, 0.55199846, 0.60238254,
        0.64764548, 0.68284551, 0.70752073, 0.72337744, 0.72509271,
        0.70508123, 0.67445078, 0.63414979, 0.60870101, 0.55833935]),
 array([0.26255734, 0.27047898, 0.29774392, 0.33716149, 0.38178989,
        0.43165603, 0.49251111, 0.55199846, 0.60238254, 0.64764548,
        0.68284551, 0.70752073, 0.72337744

In [29]:
y_train

[0.6087010139149854,
 0.5583393498567245,
 0.47952887258572974,
 0.40679695242536906,
 0.3527939837755665,
 0.3030354668448455,
 0.2765485634335888,
 0.2596425064014314,
 0.2652546895249712,
 0.291008399216133,
 0.3262689632595954,
 0.371946707803244,
 0.4208733749781387,
 0.47832706269591074,
 0.5325497652434786,
 0.5783799782059847,
 0.6160531307596065,
 0.6425871200060987,
 0.6591523652784567,
 0.6670403637717098,
 0.6676345421687288,
 0.6499908070512158,
 0.6233536774037319,
 0.5857814230684718,
 0.562808019838832,
 0.5143948124862666,
 0.444999260079732,
 0.3772001417059422,
 0.32141239568245317,
 0.27438037283012773,
 0.24953698928685142,
 0.22889545599268157,
 0.2235388816889914,
 0.2274851231182482,
 0.24283958977026598,
 0.27847011394772125,
 0.3294528625945641,
 0.38671820697139425,
 0.4369543088023605,
 0.48299528693211113,
 0.5214576877715843,
 0.5531240330587407,
 0.576075014462078,
 0.5931156024520509,
 0.6008331950654046,
 0.5899922420480993,
 0.5653461705762858,
 0.5341